### PR TITLE
Bind Fortran subroutines to a particular name

### PR DESCRIPTION
**Pull request by spakin**
This change enables sw4lite to build with Flang + Clang.

### CODE REVIEW

**Comment by andersp** [comment]
The suggested use of the bind mechanism may result in linking problems on other compilers. These problems are usually related to the Fortran compiler adding, or not adding, underscores to the object name. Often there is a compiler flag for controlling this behavior and it would be preferable to fix it by modifying the make.inc file.

**Comment by spakin** [comment]
Isn't the bind mechanism the standard Fortran mechanism for Fortran-C interaction?  I'd think it ought to work on _all_ compilers/linkers, but I admit I've tested only the Flang + Clang combination so far.

**Comment by andersp** [comment]
The bind(c) mechanism is the standard way of interfacing C and Fortran routines and we are already using it. You explicitly add the name of the object. That should not be needed when using compatible C and Fortran compilers. Specifying the name should only be needed in rare cases, for example when replacing a mixed case C routine by a Fortran routine.

**Comment by spakin** [comment]
Here's what I'm seeing when I try to build the unmodified SW4lite with [Flang](https://github.com/flang-compiler/flang) + [Clang](http://clang.llvm.org/):
```bash
$ nm optimize/EW-dg.o | grep get_comm_sides
                 U get_comm_sides
$ nm optimize/dgmodule.o | grep get_comm_sides
0000000000000010 T dgmodule_get_comm_sides
```
As you can see, this isn't an underscore problem.  Flang is prepending the module name to the symbol, and Clang doesn't expect to see that.  Ergo, link failure.

I'll ask around to see if there's some way to make Flang and Clang play better together.  In the meantime, feel free to close this pull request.

**Comment by andersp** [comment]
The problem with flang seems to be that it prepends the object by the module name. Other compilers don't normally do that. But I tested your changes on two other compilers (Apple LLVM with gfortran and Intel v.18) and it seems to work there too. Your pull request is now merged with master. Thanks for your contribution.

**Pull request merged**
